//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.35317
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.18020.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Entries {
    
    private EntriesXitem[] xitemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("x-item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
    public EntriesXitem[] xitem {
        get {
            return this.xitemField;
        }
        set {
            this.xitemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class EntriesXitem {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Converter {
    
    private ConverterAccountToEntryConverter[] accountToEntryConverterField;
    
    private ConverterItemToEntryConverter[] itemToEntryConverterField;
    
    private ConverterFileToEntryConverter[] fileToEntryConverterField;
    
    private ConverterTrivialConverter[] trivialConverterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AccountToEntryConverter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ConverterAccountToEntryConverter[] AccountToEntryConverter {
        get {
            return this.accountToEntryConverterField;
        }
        set {
            this.accountToEntryConverterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemToEntryConverter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ConverterItemToEntryConverter[] ItemToEntryConverter {
        get {
            return this.itemToEntryConverterField;
        }
        set {
            this.itemToEntryConverterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FileToEntryConverter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ConverterFileToEntryConverter[] FileToEntryConverter {
        get {
            return this.fileToEntryConverterField;
        }
        set {
            this.fileToEntryConverterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TrivialConverter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ConverterTrivialConverter[] TrivialConverter {
        get {
            return this.trivialConverterField;
        }
        set {
            this.trivialConverterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ConverterAccountToEntryConverter {
    
    private string transformsAEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransformsAE {
        get {
            return this.transformsAEField;
        }
        set {
            this.transformsAEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ConverterItemToEntryConverter {
    
    private string transformsIEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransformsIE {
        get {
            return this.transformsIEField;
        }
        set {
            this.transformsIEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ConverterFileToEntryConverter {
    
    private string rootField;
    
    private string transformsFEField;
    
    private ConverterFileToEntryConverterTransformsInstallerConfigurationTransformOptionsBehaviourOptions[][][][] transformsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Root {
        get {
            return this.rootField;
        }
        set {
            this.rootField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransformsFE {
        get {
            return this.transformsFEField;
        }
        set {
            this.transformsFEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("InstallerConfigurationTransform", typeof(ConverterFileToEntryConverterTransformsInstallerConfigurationTransformOptionsBehaviourOptions[][]), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    [System.Xml.Serialization.XmlArrayItemAttribute("Options", typeof(ConverterFileToEntryConverterTransformsInstallerConfigurationTransformOptionsBehaviourOptions[]), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false, NestingLevel=1)]
    [System.Xml.Serialization.XmlArrayItemAttribute("BehaviourOptions", typeof(ConverterFileToEntryConverterTransformsInstallerConfigurationTransformOptionsBehaviourOptions), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false, NestingLevel=2)]
    public ConverterFileToEntryConverterTransformsInstallerConfigurationTransformOptionsBehaviourOptions[][][][] Transforms {
        get {
            return this.transformsField;
        }
        set {
            this.transformsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ConverterFileToEntryConverterTransformsInstallerConfigurationTransformOptionsBehaviourOptions {
    
    private string itemModeField;
    
    private string itemMergeModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ItemMode {
        get {
            return this.itemModeField;
        }
        set {
            this.itemModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ItemMergeMode {
        get {
            return this.itemMergeModeField;
        }
        set {
            this.itemMergeModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ConverterTrivialConverter {
    
    private string transformsTVField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string TransformsTV {
        get {
            return this.transformsTVField;
        }
        set {
            this.transformsTVField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Include {
    
    private IncludeItemNameFilter[] itemNameFilterField;
    
    private IncludeItemDateFilter[] itemDateFilterField;
    
    private IncludeItemPublishFilter[] itemPublishFilterField;
    
    private IncludeItemTemplateFilter[] itemTemplateFilterField;
    
    private IncludeItemUserFilter[] itemUserFilterField;
    
    private IncludeItemLanguageFilter[] itemLanguageFilterField;
    
    private IncludeFileNameFilter[] fileNameFilterField;
    
    private IncludeFileDateFilter[] fileDateFilterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemNameFilter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public IncludeItemNameFilter[] ItemNameFilter {
        get {
            return this.itemNameFilterField;
        }
        set {
            this.itemNameFilterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemDateFilter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public IncludeItemDateFilter[] ItemDateFilter {
        get {
            return this.itemDateFilterField;
        }
        set {
            this.itemDateFilterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemPublishFilter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public IncludeItemPublishFilter[] ItemPublishFilter {
        get {
            return this.itemPublishFilterField;
        }
        set {
            this.itemPublishFilterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemTemplateFilter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public IncludeItemTemplateFilter[] ItemTemplateFilter {
        get {
            return this.itemTemplateFilterField;
        }
        set {
            this.itemTemplateFilterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemUserFilter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public IncludeItemUserFilter[] ItemUserFilter {
        get {
            return this.itemUserFilterField;
        }
        set {
            this.itemUserFilterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemLanguageFilter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public IncludeItemLanguageFilter[] ItemLanguageFilter {
        get {
            return this.itemLanguageFilterField;
        }
        set {
            this.itemLanguageFilterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FileNameFilter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public IncludeFileNameFilter[] FileNameFilter {
        get {
            return this.fileNameFilterField;
        }
        set {
            this.fileNameFilterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FileDateFilter", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public IncludeFileDateFilter[] FileDateFilter {
        get {
            return this.fileDateFilterField;
        }
        set {
            this.fileDateFilterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class IncludeItemNameFilter {
    
    private string patternField;
    
    private string filterSearchTypeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Pattern {
        get {
            return this.patternField;
        }
        set {
            this.patternField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FilterSearchType {
        get {
            return this.filterSearchTypeField;
        }
        set {
            this.filterSearchTypeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class IncludeItemDateFilter {
    
    private string filterTypeField;
    
    private string notOlderThanField;
    
    private string actionDateToField;
    
    private string actionDateFromField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FilterType {
        get {
            return this.filterTypeField;
        }
        set {
            this.filterTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NotOlderThan {
        get {
            return this.notOlderThanField;
        }
        set {
            this.notOlderThanField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ActionDateTo {
        get {
            return this.actionDateToField;
        }
        set {
            this.actionDateToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ActionDateFrom {
        get {
            return this.actionDateFromField;
        }
        set {
            this.actionDateFromField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class IncludeItemPublishFilter {
    
    private string publishDateField;
    
    private string checkWorkflowField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PublishDate {
        get {
            return this.publishDateField;
        }
        set {
            this.publishDateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CheckWorkflow {
        get {
            return this.checkWorkflowField;
        }
        set {
            this.checkWorkflowField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class IncludeItemTemplateFilter {
    
    private string templatesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Templates {
        get {
            return this.templatesField;
        }
        set {
            this.templatesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class IncludeItemUserFilter {
    
    private string filterTypeField;
    
    private string accountsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FilterType {
        get {
            return this.filterTypeField;
        }
        set {
            this.filterTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Accounts {
        get {
            return this.accountsField;
        }
        set {
            this.accountsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class IncludeItemLanguageFilter {
    
    private string languagesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Languages {
        get {
            return this.languagesField;
        }
        set {
            this.languagesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class IncludeFileNameFilter {
    
    private string patternField;
    
    private string acceptDirectoriesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Pattern {
        get {
            return this.patternField;
        }
        set {
            this.patternField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AcceptDirectories {
        get {
            return this.acceptDirectoriesField;
        }
        set {
            this.acceptDirectoriesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class IncludeFileDateFilter {
    
    private string filterTypeField;
    
    private string actionDateToField;
    
    private string actionDateFromField;
    
    private string notOlderThanField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FilterType {
        get {
            return this.filterTypeField;
        }
        set {
            this.filterTypeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ActionDateTo {
        get {
            return this.actionDateToField;
        }
        set {
            this.actionDateToField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ActionDateFrom {
        get {
            return this.actionDateFromField;
        }
        set {
            this.actionDateFromField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string NotOlderThan {
        get {
            return this.notOlderThanField;
        }
        set {
            this.notOlderThanField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class project {
    
    private string saveProjectField;
    
    private string includeField;
    
    private string excludeField;
    
    private string nameField;
    
    private projectMetadataMetadata[][] metadataField;
    
    private projectSources[] sourcesField;
    
    private Converter[] converterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SaveProject {
        get {
            return this.saveProjectField;
        }
        set {
            this.saveProjectField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Include {
        get {
            return this.includeField;
        }
        set {
            this.includeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Exclude {
        get {
            return this.excludeField;
        }
        set {
            this.excludeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    [System.Xml.Serialization.XmlArrayItemAttribute("metadata", typeof(projectMetadataMetadata), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
    public projectMetadataMetadata[][] Metadata {
        get {
            return this.metadataField;
        }
        set {
            this.metadataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Sources", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public projectSources[] Sources {
        get {
            return this.sourcesField;
        }
        set {
            this.sourcesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Converter")]
    public Converter[] Converter {
        get {
            return this.converterField;
        }
        set {
            this.converterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class projectMetadataMetadata {
    
    private string packageNameField;
    
    private string authorField;
    
    private string versionField;
    
    private string revisionField;
    
    private string licenseField;
    
    private string commentField;
    
    private string attributesField;
    
    private string readmeField;
    
    private string publisherField;
    
    private string postStepField;
    
    private string packageIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PackageName {
        get {
            return this.packageNameField;
        }
        set {
            this.packageNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Author {
        get {
            return this.authorField;
        }
        set {
            this.authorField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Version {
        get {
            return this.versionField;
        }
        set {
            this.versionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Revision {
        get {
            return this.revisionField;
        }
        set {
            this.revisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string License {
        get {
            return this.licenseField;
        }
        set {
            this.licenseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Comment {
        get {
            return this.commentField;
        }
        set {
            this.commentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Attributes {
        get {
            return this.attributesField;
        }
        set {
            this.attributesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Readme {
        get {
            return this.readmeField;
        }
        set {
            this.readmeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Publisher {
        get {
            return this.publisherField;
        }
        set {
            this.publisherField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PostStep {
        get {
            return this.postStepField;
        }
        set {
            this.postStepField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PackageID {
        get {
            return this.packageIDField;
        }
        set {
            this.packageIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class projectSources {
    
    private projectSourcesAccounts[] accountsField;
    
    private projectSourcesItems[] itemsField;
    
    private projectSourcesFiles[] filesField;
    
    private projectSourcesXitems[] xitemsField;
    
    private projectSourcesXfiles[] xfilesField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("accounts", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public projectSourcesAccounts[] accounts {
        get {
            return this.accountsField;
        }
        set {
            this.accountsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("items", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public projectSourcesItems[] items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("files", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public projectSourcesFiles[] files {
        get {
            return this.filesField;
        }
        set {
            this.filesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("xitems", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public projectSourcesXitems[] xitems {
        get {
            return this.xitemsField;
        }
        set {
            this.xitemsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("xfiles", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public projectSourcesXfiles[] xfiles {
        get {
            return this.xfilesField;
        }
        set {
            this.xfilesField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class projectSourcesAccounts {
    
    private string includeField;
    
    private string excludeField;
    
    private string nameField;
    
    private EntriesXitem[][] entriesField;
    
    private Converter[] converterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Include {
        get {
            return this.includeField;
        }
        set {
            this.includeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Exclude {
        get {
            return this.excludeField;
        }
        set {
            this.excludeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("x-item", typeof(EntriesXitem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EntriesXitem[][] Entries {
        get {
            return this.entriesField;
        }
        set {
            this.entriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Converter")]
    public Converter[] Converter {
        get {
            return this.converterField;
        }
        set {
            this.converterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class projectSourcesItems {
    
    private string skipVersionsField;
    
    private string excludeField;
    
    private string nameField;
    
    private string databaseField;
    
    private string rootField;
    
    private Converter[] converterField;
    
    private Include[] includeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SkipVersions {
        get {
            return this.skipVersionsField;
        }
        set {
            this.skipVersionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Exclude {
        get {
            return this.excludeField;
        }
        set {
            this.excludeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Database {
        get {
            return this.databaseField;
        }
        set {
            this.databaseField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Root {
        get {
            return this.rootField;
        }
        set {
            this.rootField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Converter")]
    public Converter[] Converter {
        get {
            return this.converterField;
        }
        set {
            this.converterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Include")]
    public Include[] Include {
        get {
            return this.includeField;
        }
        set {
            this.includeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class projectSourcesFiles {
    
    private string rootField;
    
    private string excludeField;
    
    private string nameField;
    
    private Include[] includeField;
    
    private Converter[] converterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Root {
        get {
            return this.rootField;
        }
        set {
            this.rootField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Exclude {
        get {
            return this.excludeField;
        }
        set {
            this.excludeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Include")]
    public Include[] Include {
        get {
            return this.includeField;
        }
        set {
            this.includeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Converter")]
    public Converter[] Converter {
        get {
            return this.converterField;
        }
        set {
            this.converterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class projectSourcesXitems {
    
    private string skipVersionsField;
    
    private string includeField;
    
    private string excludeField;
    
    private string nameField;
    
    private EntriesXitem[][] entriesField;
    
    private Converter[] converterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SkipVersions {
        get {
            return this.skipVersionsField;
        }
        set {
            this.skipVersionsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Include {
        get {
            return this.includeField;
        }
        set {
            this.includeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Exclude {
        get {
            return this.excludeField;
        }
        set {
            this.excludeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("x-item", typeof(EntriesXitem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EntriesXitem[][] Entries {
        get {
            return this.entriesField;
        }
        set {
            this.entriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Converter")]
    public Converter[] Converter {
        get {
            return this.converterField;
        }
        set {
            this.converterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class projectSourcesXfiles {
    
    private string includeField;
    
    private string excludeField;
    
    private string nameField;
    
    private EntriesXitem[][] entriesField;
    
    private Converter[] converterField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Include {
        get {
            return this.includeField;
        }
        set {
            this.includeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Exclude {
        get {
            return this.excludeField;
        }
        set {
            this.excludeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("x-item", typeof(EntriesXitem), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public EntriesXitem[][] Entries {
        get {
            return this.entriesField;
        }
        set {
            this.entriesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Converter")]
    public Converter[] Converter {
        get {
            return this.converterField;
        }
        set {
            this.converterField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.18020")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Converter", typeof(Converter))]
    [System.Xml.Serialization.XmlElementAttribute("Entries", typeof(Entries))]
    [System.Xml.Serialization.XmlElementAttribute("Include", typeof(Include))]
    [System.Xml.Serialization.XmlElementAttribute("project", typeof(project))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
